# Generated by Django 2.0.7 on 2018-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('upvote', models.PositiveIntegerField()),
                ('downvote', models.PositiveIntegerField()),
            ],
        ),
    ]
