# Generated by Django 2.0.7 on 2018-07-18 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 5, 36, 17, 243675)),
        ),
        migrations.AlterField(
            model_name='container',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
