# Generated by Django 2.0.7 on 2018-07-19 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180718_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 19, 23, 32, 748246)),
        ),
    ]
